unit_costs = {
    "archer_queen": 5,
    "archer": 2,
    "bandit": 4,
    "barbarian": 2,
    "bomber": 2,
    "dart_goblin": 3,
    "executioner": 3,
    "giant_skeleton": 3,
    "goblin_machine": 4,
    "goblin": 2,
    "golden_knight": 5,
    "knight": 2,
    "mega_knight": 4,
    "pekka": 3,
    "prince": 3,
    "princess": 4,
    "royal_ghost": 4,
    "skeleton_king": 5,
    "spear_goblin": 2,
    "valkyrie": 3,   
}
